/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package changeprone;

import java.io.BufferedReader;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import javax.swing.filechooser.FileNameExtensionFilter;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import jxl.write.Label;
import jxl.write.Number;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;

/**
 *
 * @author aryan_000
 */
public class UploadFolder extends javax.swing.JFrame {

    /**
     * Creates new form UploadFolder
     * @param folder
     */
//    ArrayList filenames = new ArrayList();
    ArrayList<Files> filenames = new ArrayList<>();
    
    
    public void listofFiles( File folder)
{
    for(File testfile : folder.listFiles())
    {
        if(testfile.isDirectory())
        {
            listofFiles(testfile);
        }
        else
        {
//            System.out.println(testfile);
//            System.out.println(testfile.getName());
//            System.out.println("Size of the file is : " + testfile.length() + "Bytes");
        
         
            String ext = null  ;
            String temp = testfile.getPath();
            int i = temp.lastIndexOf('.');
            if(i>0)
                ext = temp.substring(i+1);
            
            if(ext.equals("java"))
            {
//                JOptionPane.showMessageDialog(null,"File name is : " + testfile.getName());
                 filenames.add(new Files(testfile.getName(),testfile.length(),testfile , testfile.getPath()));
                 
            }
        }
    }
} // end of listfo files function
    
    public void sortByName()
    {
         Collections.sort(filenames, (Files o1, Files o2) -> o1.Filename.compareTo(o2.Filename));
    } 
    
    

    public UploadFolder() {
        initComponents();
       
        filetable.setVisible(false);
        
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selectfolder = new javax.swing.JButton();
        process = new javax.swing.JButton();
        filetable = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        FileDetails = new javax.swing.JTable();
        uploadanotherversion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText(" Change Proneness");

        selectfolder.setText("Select Folder");
        selectfolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectfolderActionPerformed(evt);
            }
        });

        process.setText("Process");
        process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processActionPerformed(evt);
            }
        });

        filetable.setVisible(true);

        FileDetails.setAutoCreateRowSorter(true);
        FileDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No", "File Names", "File Size", "File Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(FileDetails);

        javax.swing.GroupLayout filetableLayout = new javax.swing.GroupLayout(filetable.getContentPane());
        filetable.getContentPane().setLayout(filetableLayout);
        filetableLayout.setHorizontalGroup(
            filetableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        filetableLayout.setVerticalGroup(
            filetableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        uploadanotherversion.setText("Upload Another Version");
        uploadanotherversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadanotherversionActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText(" New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                non(evt);
            }
        });
        jMenu3.add(About);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(selectfolder, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(process, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(uploadanotherversion))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(filetable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filetable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectfolder, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(process, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadanotherversion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
    private void selectfolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectfolderActionPerformed
        String userDir = System.getProperty("user.home");
        JFileChooser folder = new JFileChooser(userDir+"/Desktop");
        folder.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        folder.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter xmlfilter = new FileNameExtensionFilter(
     "Excel Files  (*.xls)", "xls");
        folder.setFileFilter(xmlfilter);
        int returnvalue = folder.showSaveDialog(this);
        
        File myfolder = null;
        if(returnvalue == JFileChooser.APPROVE_OPTION)
        {
            myfolder = folder.getSelectedFile();
//            System.out.println(myfolder);         
        }
        
        
       
        if(myfolder!=null)
        {
            JOptionPane.showMessageDialog(null,"The current choosen file directory is : " + myfolder);
        }
        
        listofFiles(myfolder);
        sortByName();
    }//GEN-LAST:event_selectfolderActionPerformed

    /**
     *
     * @param f
     * @return
     * @throws IOException
     */
    public  int getLines(File f) throws IOException {
        FileReader fr;
        fr = new FileReader(f);
        BufferedReader br;
        br = new BufferedReader(fr);
        int i = 0;
        boolean isEOF = false;
        do {
            String t = br.readLine();
            if (t != null) {
                isEOF = true;
                t = t.replaceAll("\\n|\\t|\\s", "");
                if ((!t.equals("")) && (!t.startsWith("//"))) {
                    i = i + 1;
                }
            } else {
                isEOF = false;
            }
        } while (isEOF);
        br.close();
        fr.close();
        return i;
    }
    public void addsheet( WritableWorkbook workbook , File f ) throws IOException, WriteException, BiffException
    {       
        System.out.println("Adding when the file does not exist");
            workbook = Workbook.createWorkbook(f);
            int sheetno = workbook.getNumberOfSheets();
            
            String version = "version " +  sheetno ;
//            System.out.println(sheetno);
            WritableSheet sheet = workbook.createSheet(version, 0);
            
            int count = 1;
            int row =  0 ;
            int column = 0;
           // sheet.addCell(new Label (column++,row ,"S.No"));
            sheet.addCell(new Label ( column++ ,row, "Filename "));
            //sheet.addCell(new Label(column++ ,row, "File Size "));
           // sheet.addCell(new Label(column++ ,row, "Location "));
            sheet.addCell(new Label(column++ , row , "LOC"));
            sheet.addCell(new Label(column++ , row , "BOC"));
            
            row++;
            column = 0;
             
            Boc.curr_version  = 1;
            for (Files filename : filenames) 
            {
//                String size = Long.toString(filename.Filesize) + "  Bytes";
//                System.out.println(filename.Filename);
               // Number sno = new Number(column++ , row , count++);
//                Label sno = new Label (column++,row ,Integer.toString(count++));
                Label fname = new Label ( column++ ,row, filename.Filename);
//                Label colsize = new Label(column++ ,row, size);
                //Label location = new Label(column++ ,row, filename.FileLocation);
                File ans =  new File(filename.FileLocation);
                Number loc = new Number(column++ , row , getLines(ans));
             //   sheet.addCell(sno);
                sheet.addCell(fname);
                sheet.addCell(loc);
               // sheet.addCell(colsize);
                //sheet.addCell(location);
              
                int boc_value  ;
                
                if(Boc.bocMap.containsKey(filename.Filename))
                {boc_value  = Boc.bocMap.get(filename.Filename);
                    
                }
                else 
                {
                    boc_value = Boc.curr_version;
                    
                    Boc.bocMap.put(filename.Filename, boc_value);
                }
                System.out.println( filename.Filename + " and " + boc_value);
                
                
                
                Number boc = new Number(column++ , row , boc_value);
                sheet.addCell(boc);
                row++;
                column = 0;
                
            }
            
            workbook.write();
            workbook.close();
            
            System.out.println("finished when the file does not exist");
            
        /*     Set set = Boc.bocMap.entrySet();
         Iterator it = set.iterator();
         
         while(it.hasNext()) {
         Map.Entry me = (Map.Entry)it.next();
         System.out.println(me.getKey() + ": " + me.getValue());
         
         }
         */
         System.out.println("finishes adding boc");
         
//         FchAndLchAndCho cho = new FchAndLchAndCho();
//           cho.addCho(f);
            
    }
    
    
    public void addsheet(Workbook workbook1 ,File f) throws IOException, WriteException, BiffException
    {   
        System.out.println("adding when file exists");
        
       /*  Set set = Boc.bocMap.entrySet();
         Iterator it = set.iterator();
         
         while(it.hasNext()) {
         Map.Entry me = (Map.Entry)it.next();
         System.out.println(me.getKey() + ": " + me.getValue());
         
         }
        */ 
          WritableWorkbook workbook = Workbook.createWorkbook(f, workbook1);
            int sheetno = workbook.getNumberOfSheets();
            
            
            for(int i =0;i<sheetno; i++)
            {
                WritableSheet sheet2 = workbook.getSheet(i);
            }
            
//            workbook.write();
            
            System.out.println(sheetno);
            String version = "version " + sheetno;
            WritableSheet sheet = workbook.createSheet(version, sheetno+1);
            Boc.curr_version  = sheetno + 1;
            int count = 1;
            int row =  0 ;
            int column = 0;
          //  sheet.addCell(new Label (column++,row ,"S.No"));
            sheet.addCell(new Label ( column++ ,row, "Filename "));
            //sheet.addCell(new Label(column++ ,row, "File Size "));
            //sheet.addCell(new Label(column++ ,row, "Location "));
            sheet.addCell(new Label(column++ , row , "LOC"));
            sheet.addCell(new Label(column++ , row , "BOC"));
            row++;
            column = 0;
             
            for (Files filename : filenames) 
            {
                String size = Long.toString(filename.Filesize) + "  Bytes";
//                System.out.println(filename.Filename);
                //Number sno = new Number(column++ , row , count++);
//                Label sno = new Label (column++,row ,Integer.toString(count++));
                Label fname = new Label ( column++ ,row, filename.Filename);
               // Label colsize = new Label(column++ ,row, size);
               // Label location = new Label(column++ ,row, filename.FileLocation);
                File ans =  new File(filename.FileLocation);
                
                Number loc = new Number(column++ , row , getLines(ans));
               // sheet.addCell(sno);
                sheet.addCell(fname);
               // sheet.addCell(colsize);
               // sheet.addCell(location);
                sheet.addCell(loc);
                
                int boc_value  ;
                
                if(Boc.bocMap.containsKey(filename.Filename))
                {
                    boc_value  = Boc.bocMap.get(filename.Filename);
                    System.out.println(filename.Filename + " found");
                }
                else 
                {
                    boc_value = Boc.curr_version;
                }
                System.out.println( filename.Filename + " and " + boc_value);
                
                
                
                Number boc = new Number(column++ , row , boc_value);
                sheet.addCell(boc);
                row++;
                column = 0;
                
            }
            
            workbook.write();
            workbook.close();
            workbook1.close();
            System.out.println("finished when the file already exists");
            
//           FchAndLchAndCho cho = new FchAndLchAndCho();
//           cho.addCho(f);
//           cho.addFchAndLch(f);
    }
    
    
    
    private void processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processActionPerformed
        
        try {
          filetable.setVisible(true);
          File f = new File("C:\\Users\\aryan_000\\Desktop\\output.xls");
            
          
             if(!f.exists())
             {  System.out.println("File does not exist");
             
             WritableWorkbook workbook   = null; 
                addsheet(workbook,f);
            
             }
            else          { 
              System.out.println("File cannot be created ");
               Workbook workbook = Workbook.getWorkbook(f);
              addsheet(workbook,f);
              workbook.close();
          }
          

            int count = 1;
            DefaultTableModel model = (DefaultTableModel) FileDetails.getModel();
            
            for (Files filename : filenames) 
            {
                String size = Long.toString(filename.Filesize) + "Bytes";
                model.addRow(new Object[]{count++,filename.Filename, size  , filename.FileLocation});
            }
            
            
            JOptionPane.showMessageDialog(null,"Total number of files are : " + filenames.size());
            filenames.clear();
        } catch (IOException | WriteException | BiffException ex) {
            Logger.getLogger(UploadFolder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_processActionPerformed

    private void non(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_non
        // TODO add your handling code here:
    }//GEN-LAST:event_non

    private void uploadanotherversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadanotherversionActionPerformed
            // TODO add your handling code here:
        filetable.setVisible(false);
         JOptionPane.showMessageDialog(null,"Upload Another Version");
         
    }//GEN-LAST:event_uploadanotherversionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UploadFolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UploadFolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UploadFolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UploadFolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UploadFolder().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JTable FileDetails;
    private javax.swing.JInternalFrame filetable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton process;
    private javax.swing.JButton selectfolder;
    private javax.swing.JButton uploadanotherversion;
    // End of variables declaration//GEN-END:variables





}
